export const EXAMPLE_REGISTRY: Record<string, string> = {
  "Napoli Elite Pizza": "napoli-elite-pizza.html",
  "FinTrack Analytics": "fintrack-analytics.html",
  "Photo Library": "photo-library.html",
  "Traceform Home": "traceform-home.html",
  "Traceform Explore": "traceform-explore.html",
  "Traceform Methodology": "traceform-methodology.html",
  "Traceform Use Cases": "traceform-use-cases.html",
  "Plant Care Dashboard": "plant-care-dashboard.html",
  "Beehive Management Dashboard": "beehive-dashboard.html",
  "Honey Production Log Entry": "honey-production-log.html",
  "ApiaryOS Pest & Disease Management": "beehive-pest-control.html",
  "Queen Bee Tracking": "queen-bee-tracking.html",
  "Beehive OS Settings": "beehive-settings.html",
  "My Plants - Plant Details": "my-plants-details.html",
  "Add New Plant - PlantCare": "plant-care-add-plant.html",
  "Plant Library": "plant-care-library.html",
  "PlantPal - Settings": "plant-care-settings.html",
  "SignalAtlas - Landing Page": "signal-atlas-landing.html",
  "SignalAtlas - Data Intelligence Platform": "signal-atlas-data-platform.html",
};
